spring:
  application:
    name: dahaeng

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dahaeng
    username: your-db-username
    password: your-db-password

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: true
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/dahaeng}

  jwt:
    secret: your-jwt-secret-base64
    access-expiration: 360000000
    refresh-expiration: 604800000

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: your-google-client-id
            client-secret: your-google-client-secret
            scope: profile,email,https://www.googleapis.com/auth/youtube.readonly
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/google

app:
  front-callback-url: http://localhost:8080/
