spring.application.name=dahaeng

# registration
spring.security.oauth2.client.registration.google.client-id=800167123778-ppuuodmbdg3co7qoffenepfpvkqeck70.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email,https://www.googleapis.com/auth/youtube.readonly
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code

spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=1111


spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.jwt.secret=Y3VzdG9tLXNlY3JldC1rZXktZm9yLWp3dC1zaWduaW5n
spring.jwt.access-expiration=360000000
spring.jwt.refresh-expiration=604800000
